export const loginSeoConfig = {
  title: 'Log In | VeoLMS',
  description: 'Log in to your VeoLMS account to access your courses, track your progress, and continue learning.',
  keywords: ['login', 'signin', 'VeoLMS login', 'online learning account'],
  canonical: 'https://veolms.com/login',
  robots: 'index, follow',
  openGraph: {
    type: 'website',
    url: 'https://veolms.com/login',
    title: 'Log In | VeoLMS',
    description: 'Log in to your VeoLMS account to access your courses.',
    image: 'https://veolms.com/og/home-og-image.png',
    siteName: 'VeoLMS',
    locale: 'en_US',
  },
  twitterCard: {
    card: 'summary_large_image' as const,
    site: '@VeoLMS',
    creator: '@VeoLMS',
    title: 'Log In | VeoLMS',
    description: 'Log in to your VeoLMS account to access your courses.',
    image: 'https://veolms.com/og/home-og-image.png',
  },
  structuredData: {},
};

export const registerSeoConfig = {
  title: 'Sign Up | VeoLMS',
  description: 'Create a new VeoLMS account to unlock premium learning paths and courses.',
  keywords: ['signup', 'register', 'VeoLMS registration'],
  canonical: 'https://veolms.com/register',
  robots: 'index, follow',
  openGraph: {
    type: 'website',
    url: 'https://veolms.com/register',
    title: 'Sign Up | VeoLMS',
    description: 'Create a new VeoLMS account.',
    image: 'https://veolms.com/og/home-og-image.png',
    siteName: 'VeoLMS',
    locale: 'en_US',
  },
  twitterCard: {
    card: 'summary_large_image' as const,
    site: '@VeoLMS',
    creator: '@VeoLMS',
    title: 'Sign Up | VeoLMS',
    description: 'Create a new VeoLMS account.',
    image: 'https://veolms.com/og/home-og-image.png',
  },
  structuredData: {},
};

export const verifyEmailSeoConfig = {
  title: 'Verify Email | VeoLMS',
  description: 'Verify your email address to complete the registration process.',
  keywords: ['verify email', 'otp', 'VeoLMS verification'],
  canonical: 'https://veolms.com/verify-email',
  robots: 'noindex, nofollow',
  openGraph: {
    type: 'website',
    url: 'https://veolms.com/verify-email',
    title: 'Verify Email | VeoLMS',
    description: 'Verify your email address.',
    image: 'https://veolms.com/og/home-og-image.png',
    siteName: 'VeoLMS',
    locale: 'en_US',
  },
  twitterCard: {
    card: 'summary_large_image' as const,
    site: '@VeoLMS',
    creator: '@VeoLMS',
    title: 'Verify Email | VeoLMS',
    description: 'Verify your email address.',
    image: 'https://veolms.com/og/home-og-image.png',
  },
  structuredData: {},
};

export const forgotPasswordSeoConfig = {
  title: 'Forgot Password | VeoLMS',
  description: 'Reset your VeoLMS password.',
  keywords: ['forgot password', 'reset', 'VeoLMS password'],
  canonical: 'https://veolms.com/forgot-password',
  robots: 'noindex, nofollow',
  openGraph: {
    type: 'website',
    url: 'https://veolms.com/forgot-password',
    title: 'Forgot Password | VeoLMS',
    description: 'Reset your VeoLMS password.',
    image: 'https://veolms.com/og/home-og-image.png',
    siteName: 'VeoLMS',
    locale: 'en_US',
  },
  twitterCard: {
    card: 'summary_large_image' as const,
    site: '@VeoLMS',
    creator: '@VeoLMS',
    title: 'Forgot Password | VeoLMS',
    description: 'Reset your VeoLMS password.',
    image: 'https://veolms.com/og/home-og-image.png',
  },
  structuredData: {},
};

export const resetPasswordSeoConfig = {
  title: 'Reset Password | VeoLMS',
  description: 'Enter your OTP to reset your VeoLMS password.',
  keywords: ['reset password', 'otp', 'VeoLMS password reset'],
  canonical: 'https://veolms.com/reset-password',
  robots: 'noindex, nofollow',
  openGraph: {
    type: 'website',
    url: 'https://veolms.com/reset-password',
    title: 'Reset Password | VeoLMS',
    description: 'Enter your OTP to reset your VeoLMS password.',
    image: 'https://veolms.com/og/home-og-image.png',
    siteName: 'VeoLMS',
    locale: 'en_US',
  },
  twitterCard: {
    card: 'summary_large_image' as const,
    site: '@VeoLMS',
    creator: '@VeoLMS',
    title: 'Reset Password | VeoLMS',
    description: 'Enter your OTP to reset your VeoLMS password.',
    image: 'https://veolms.com/og/home-og-image.png',
  },
  structuredData: {},
};
